// Generated by Melange
'use strict';

var ToneInteropJs = require("./ToneInterop.js");
var Music = require("../music/music.js");
var Stdlib__Array = require("melange/array.js");
var Stdlib__List = require("melange/list.js");

function createPolySynth(prim) {
  return ToneInteropJs.createPolySynth();
}

function play_note(synth, note) {
  var note_str = Music.Note.to_string(note);
  synth.triggerAttackRelease(note_str, "8n");
}

function play_notes(synth, notes) {
  var note_strings = Stdlib__Array.of_list(Stdlib__List.map((function (note) {
              return Music.Note.to_string(note);
            }), notes));
  synth.triggerAttackRelease(note_strings, "8n");
}

var note = play_note;

function chord(synth, root, kind) {
  var chord$1 = Music.Chord.spell(root, kind);
  play_notes(synth, chord$1);
}

function path(synth, notes, delay) {
  var walk = function (notes) {
    if (!notes) {
      return ;
    }
    var rest = notes.tl;
    var note = notes.hd;
    setTimeout((function (param) {
            play_note(synth, note);
            walk(rest);
          }), delay);
  };
  walk(notes);
}

var Play = {
  note: note,
  chord: chord,
  path: path
};

exports.createPolySynth = createPolySynth;
exports.play_note = play_note;
exports.play_notes = play_notes;
exports.Play = Play;
/* ./ToneInterop.js Not a pure module */
